import type { Metadata } from 'next';
import './globals.css';

import { Roboto } from 'next/font/google';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
    title: 'Steam Market Crawler',
    description: 'Generated by create next app',
};

const roboto = Roboto({ subsets: ['latin'], weight: '500' });

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(roboto.className, 'dark')}>{children}</body>
        </html>
    );
}
